unional/clibuilder

package.json
src/HelpSectionBuilder.ts

Add `this` type to `HelpSectionBuilder` replaceable methods

Add this type

---

src/Action.ts
src/CliBuilder.ts
src/CommandBuilder.ts
src/index.spec.ts

and fix defaultAction override implementation.
Added tests and comments

Add defaultHelpAction

---

src/CliBuilder.ts
src/CommandBuilder.ts
src/HelpSectionBuilder.ts
src/index.spec.ts

And do not show <noActino> when there are sub commands.

Fix getCommandNames()

---

README.md
fixtures/one-plugin/node_modules/cli-plugin-x/index.js
fixtures/scoped-plugin/node_modules/@cli/y/index.js
package-lock.json
package.json
src/Cli.spec.ts
src/Cli.ts
src/PluginCli.ts
src/index.spec.ts
src/index.ts
src/interfaces.ts
src/loadPlugins.ts
src/test-util/setup.ts
src/test-util/spyDisplay.spec.ts

Improve plugin to add multiple commands

Improve API to make it more consistent.

---

README.md
src/Cli.ts
src/Command.spec.ts
src/Command.ts
src/Presenter.ts
src/loadPlugins.ts
src/parseArgv.ts
src/test-util/argCommand.ts
src/test-util/asyncCommand.ts
src/test-util/echoCommand.ts
src/test-util/echoNameOptionCommand.ts
src/test-util/errorCommand.ts
src/test-util/getDisplay.ts
src/test-util/groupOptionsCommand.ts
src/test-util/noopCommand.ts
src/test-util/optionsCommand.ts
src/test-util/verboseCommand.ts
src/util.ts

Move some interfaces into Command namespace.

BREAKING: Change CommandSpec to Command.

---

package-lock.json
package.json
src/findPlugins.spec.ts
src/loadPlugins.spec.ts
src/loadPlugins.ts

Previous attempt doesn't work. Need to actually go up to look for the parent of `node_modules` folder.

fix: global resolution

---

package-lock.json
package.json
src/Cli.spec.ts
src/index.spec.ts
src/parseArgv.ts
src/test-util/createArgs.spec.ts
src/test-util/createArgv.spec.ts
src/test-util/createArgv.ts
src/test-util/createCliArgv.ts
src/test-util/createCommandArgs.ts
src/test-util/index.ts
src/test-util/spyDisplay.spec.ts
src/test-util/stringOptionCommand.ts

rename createArgv to createCliArgv

BREAKING: add createCommandArgs

---

src/PlainPresenter.spec.ts
src/PlainPresenter.ts
src/parseArgv.spec.ts
src/parseArgv.ts

Multi char alias

---

package-lock.json
package.json
src/parseArgv.ts
src/test-util/createCommandArgs.spec.ts
src/test-util/numberOptionCommand.spec.ts
src/test-util/setup.ts
src/test-util/stringOptionCommand.spec.ts

Add setupCommandTest function.

Fix string option

---

src/Command.ts
src/Task.ts
src/createParsable.ts
src/index.spec.ts
src/interfaces.ts
src/parseArgv.groupOptions.spec.ts
src/parseArgv.options.spec.ts
src/parseArgv.spec.ts
src/parseArgv.ts
src/test-util/createCommandArgs.spec.ts
src/test-util/createCommandArgs.ts
src/test-util/numberOptionCommand.spec.ts
src/test-util/stringOptionCommand.spec.ts
src/toYargsOption.ts

So that the command can detect which is input from users and which value comes from defaults
Fixes #92

Add _defaults to `args`

---

package-lock.json
package.json
src/Cli.spec.ts
src/Cli.ts
src/index.spec.ts
src/loadPlugins.ts
src/log.ts
src/parseArgv.ts
src/util.ts

Add debug-cli option

---

.travis.yml
README.md

BREAKING Changes: Remote Task and change setupCommandTest to setupCliCommandTest

perf: trigger semantic-release

---

src/Cli.ts
src/PluginCli.spec.ts
src/PluginCli.ts
src/findPlugins.spec.ts
src/findPlugins.ts
src/loadPlugins.spec.ts
src/loadPlugins.ts

perf: makes loadPlugins() async

---

src/Display.ts

It is common to log info message in CLI.

fix: adjust normal log level to info.

---

package-lock.json
package.json
src/parseArgv.options.spec.ts
src/parseArgv.ts

`yargs-parser@11` does that. Revert back to 10

fix: camel case option will not hyphenated

---

src/CliCommand.spec.ts
src/CliCommand.ts

fix: CliCommand Context is default to indexed object.

---

package-lock.json
package.json
src/cli-command/createCliCommand.ts
src/cli/Cli.ts
src/cli/CliContext.ts
src/commands/searchPackageCommand.ts
src/index.spec.ts
src/index.ts
src/plugin-cli/PluginCli.spec.ts
src/test-util/numberOptionCommand.spec.ts
src/test-util/setup.ts

remove `createCliCommand()` from export.
It should not be in the first place.

fix: update deps

---

src/commands/getPluginCli.ts
src/commands/index.ts
src/commands/listPluginsCommand.ts
src/commands/pluginsCommand.ts
src/commands/searchPluginsCommand.spec.ts
src/commands/searchPluginsCommand.ts
src/test-util/asyncCommand.ts
src/test-util/index.ts

feat: expose searchPackagesCommand

fix: plugins search to search for cli keyword

---

src/plugin-cli/PluginCli.spec.ts
src/plugin-cli/PluginCli.ts

allow PluginCi to access ui, config, etc.

fix: specify PluginCli run scope

---

package.json
yarn.lock

Needs 1.30 for `KeyOfOptional`

fix: bump type-plus deps

---

package.json
src/cli/types.ts
src/presenter/PlainPresenter.ts
src/presenter/enquirer-types.ts
src/presenter/index.ts
src/presenter/types.ts
src/test-util/InMemoryPresenter.ts
tsconfig.base.json
yarn.lock

feat: replace inquirer with enquirer

---

src/cli/createCommand.spec.ts
src/cli/createCommand.ts
src/plugin-cli/createPluginCommand.spec.ts
src/plugin-cli/createPluginCommand.ts

so that command can specify config only

fix: make create*Command Context optinoal

---

package.json
tsconfig.base.json

fix: use tslib

---

src/presenter/PlainPresenter.ts
src/presenter/enquirer-types.ts
src/presenter/index.ts
src/presenter/types.ts
src/test-util/InMemoryPresenter.ts

the type change will cause plugin fails to compile,
but it typicaly should not break usage.
So not going to bump major version.

fix: update enquirer types

---

package.json
src/cli/createCli.spec.ts
src/cli/createCli.ts
src/errors.ts

This is breaking, but given short cycle, keep it as a fix.
As just trying to make the API more coherient.
Add src to dist for F12

fix: rename ProcessError to CliError

---

src/create-plugin-cli/createPluginCli.ts
src/create-plugin-cli/createPluginCommand.ts
src/create-plugin-cli/listPluginsCommand.ts
src/create-plugin-cli/loadPlugins.ts
src/create-plugin-cli/types.ts
src/test-util/createCommandTest.spec.ts
src/test-util/createPluginCliTest.ts

So that it will work with createCommandTest()

fix: adjust PluginCli command type

---

src/create-cli/createCommand.ts
src/create-plugin-cli/createPluginCommand.ts
src/test-util/setupCommandTest.spec.ts

from return valueof createCommand() and createPluginCommand().

fix: also remove argument and option types

---

.editorconfig

BREAKING CHANGE: complete rewrite

fix: release v7

---

src/builder.spec.ts
src/builder.ts
src/commands.ts
src/lookupCommand.spec.ts
src/lookupCommand.ts
src/state.ts
src/ui.ts

the command was not shown
fixes #331

fix: sub command help

---

src/builder.spec.ts
src/builder.ts
src/context.ts
src/loadAppInfo.ts
src/loadPlugins.spec.ts
src/loadPlugins.ts
src/state.ts
src/test-utils/mockContext.ts
src/ui.spec.ts
src/ui.ts
yarn.lock

fix: clibuilder debug/info logs

---

src/builder.spec.ts
src/builder.ts
src/lookupCommand.spec.ts
src/lookupCommand.ts

also fix invalid-key for default options

fix: optional argument is not error

---

README.md

README.md in packages/clibuider/README.md now also in /README.md

updated cli builder readme to /README.md
